### PR TITLE
Add module_result method to MetricResult

### PR DESCRIPTION
**Pull request by diegoamc**
* The method will retrieve the module_result associated with the metric
 result

Signed-off-by: Heitor Reis <marcheing@gmail.com>

### CODE REVIEW

**Comment by rafamanzo** [comment]
Looks like there is some kind of dead lock the Travis build dies while processing (I've already restarted twice each).

**Comment by diegoamc** [comment]
Could you try to run the tests on your computer? I can't reproduce the error here.

**Comment by marcheing** [comment]
I also cannot reproduce the bug on my machine

**Comment by marcheing** [comment]
This pull request now depends on https://github.com/mezuro/kalibro_client_py/pull/64

**Pull request merged**
