### PR TITLE
Implement Metric collector details

### PR DESCRIPTION
**Pull request by diegoamc**
Signed off by: @danielkza

### CODE REVIEW

**Comment by rafamanzo** [comment]
The build should fail? Is it just some transient fail?

**Comment by diegoamc** [comment]
No, it should pass.
Maybe Analizo is not being correctly installed by Travis. Or maybe the cache is not working. @danielkza We need to see what is the problem. On our local environment, all tests pass.

**Comment by rafamanzo** [comment]
I think analizo is not installed at all. Otherwise we would not be able to
use Travis containers.

Maybe we should refactor testes that rely on Analizo to rely on metric_fu

**Comment by diegoamc** [comment]
Ok, I'll make the modifications and push a commit.

**Comment by diegoamc** [comment]
Done.

**Pull request merged**
